conda/conda-pack

.gitignore, .travis.yml, conda_pack/core.py, conda_pack/tests/test_core.py, testing/break_package_cache.py, testing/ci/install_conda.sh, testing/env_yamls/py27.yml, testing/env_yamls/py36.yml, testing/setup_envs.sh, testing/test_packages/conda_pack_test_lib1/conda.recipe/meta.yaml, testing/test_packages/conda_pack_test_lib1/conda_pack_test_lib1/cli.py, testing/test_packages/conda_pack_test_lib1/setup.py, testing/test_packages/conda_pack_test_lib2/conda.recipe/meta.yaml, testing/test_packages/conda_pack_test_lib2/conda_pack_test_lib2/cli.py, testing/test_packages/conda_pack_test_lib2/setup.py
Add test infrastructure and some basic tests.
=> Add testing

conda_pack/cli.py, conda_pack/core.py, conda_pack/tests/test_core.py
Allows for overwriting existing archives. Fixes #22.
=> Add --force flag

.travis.yml, conda_pack/cli.py, conda_pack/core.py, conda_pack/formats.py, conda_pack/tests/conftest.py, conda_pack/tests/test_core.py
Needed for compatibility with some unzip implementations.
=> Add option to disable zip64 extensions

conda_pack/core.py, conda_pack/tests/test_core.py
Slightly improved user experience.
=> Add --help and --version to conda-unpack command

conda_pack/core.py, conda_pack/tests/test_core.py
=> Error if packaging root environment

conda_pack/core.py
=> Use absolute path for computing new prefix

conda_pack/core.py, conda_pack/scripts/posix/activate, conda_pack/scripts/posix/deactivate, conda_pack/tests/conftest.py, conda_pack/tests/test_core.py, testing/env_yamls/nopython.yml, testing/setup_envs.sh
Additionally add support for activate/deactivate scripts.
Fixes #36.
=> Support packaging environments without Python

docs/source/index.rst
=> Remove "windows unsupported" comment in docs

conda_pack/cli.py, conda_pack/core.py, conda_pack/tests/test_core.py
=> Add option to ignore editable packages

conda_pack/prefixes.py
=> Fixing #80, merging #100

.github/workflows/main.yml, conda_pack/tests/conftest.py
Builds the docs (to make sure they are correct) and flake8's the pack in the github action
=> Add flake8 check and docs build test

.github/workflows/cleanup.yml
GitHub actions doesn't have a native way to delete an artifact once in a standard workflow. Until that comes we need a cleanup job like this
=> add artifact cleanup

.github/workflows/cleanup.yml, .github/workflows/docs.yml, .github/workflows/main.yml
=> Deploy docs

.github/workflows/docs.yml, .github/workflows/main.yml
Hoping this fixes the versioning problem in package and doc builds
=> Add full fetch for package & doc build

.github/workflows/main.yml
Silly mistake on my part, but still, I'm learning a lot about GitHub actions for future work.
=> We don't need to download conda.exe, we have one

docs/source/index.rst, testing/env_yamls/has_conda.yml, testing/env_yamls/py36_broken.yml
Covers one of the tasks in #130
=> Improve language to reduce impression of relocatability

.github/workflows/main.yml, conda-recipe/meta.yaml, conda_pack/cli.py, conda_pack/compat.py, conda_pack/core.py, conda_pack/formats.py, conda_pack/tests/test_formats.py, docs/source/index.rst, docs/source/squashfs.rst
=> Add squashfs

conda_pack/scripts/posix/activate
=> Correct full_path_script_dir

.github/workflows/main.yml, .pre-commit-config.yaml, README.md
=> pre-commit: update, run via pre-commit.ci, add badge

.github/workflows/main.yml, README.md
Update main.yml action to fix a lot of deprecation warning.
=> Chore: Update main.yml action versions, upgrade from deprecated syntax, fix badge url

.github/CODEOWNERS
=> Add @xhochy to CODEOWNERS

conda_pack/tests/test_formats.py
=> xfail test_format[squashfs] on Mac for Py<3.9

.github/workflows/main.yml
=> Use `macos-12` runners

.github/workflows/main.yml
Fixing out of date docs
closes #352
=> Switch to official gh action for gh-pages

docs/source/conf.py
Travis CI hasn't been used for a while now.
=> Hide Travis button in docs.

.github/workflows/main.yml
=> Fix development upload, now .conda
