docs/source/spark.rst

Previously in the conda-pack part of the example we used tar.gz files
but in the Spark part of the example we used .zip files.
Now we conform to using .zip in both locations
I'm not certain that this is the right move, but it was a quick enough fix to make as a suggestion.

Use .zip file in spark documentation

---

.travis.yml
conda_pack/cli.py
conda_pack/tests/test_cli.py

Catch to avoid outputting trackeback to user.

Handle KeyboardInterrupt

---

conda_pack/core.py
conda_pack/tests/test_cli.py
conda_pack/tests/test_core.py

Fixes #5.
Also (hopefully) make interrupt test more robust.

Nicely error if conda isn't on path

---

conda_pack/core.py

Conda could just be a shell function and not a binary in `PATH`.
```
$ type -a conda
conda is a function
conda () 
{ 
if [ "$#" -lt 1 ]; then
$_CONDA_EXE;
else
\local cmd="$1";
shift;
case "$cmd" in 
activate)
_conda_activate "$@"
;;
deactivate)
_conda_deactivate "$@"
;;
install | update | uninstall | remove)
$_CONDA_EXE "$cmd" "$@" && _conda_reactivate
;;
*)
$_CONDA_EXE "$cmd" "$@"
;;
esac;
fi
}
$ echo $CONDA_EXE
/home/nwani/m3/bin/conda
$ echo $PATH
/tmp/wani.1531021259/test/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/nwani/.local/bin:/home/nwani/bin
```

Check for CONDA_EXE env var and then fallback to PATH

---

conda_pack/core.py
conda_pack/tests/conftest.py
conda_pack/tests/test_core.py
testing/env_yamls/py36_broken.yml
testing/setup_envs.sh

If pip and conda are mixed, sometimes pip will uninstall packages that
are managed by conda. This *can* lead to an inconsistent environment,
and is generally frowned upon. Instead of trying to handle these cases,
we collect packages that have been broken by pip and report a nice error
message on failure.
Fixes #34.

Error nicely if pip clobbers a conda-installed file

---

conda_pack/cli.py
conda_pack/core.py
conda_pack/tests/test_core.py
docs/source/spark.rst

This adds a new option `--dest-prefix` that allows specifying the
destination prefix before packing. In this case the prefixes are
rewritten before packing the environment, and the `conda-unpack` script
won't be generated.
This is useful for cases where you can't run the `conda-unpack` script
but know the destination path beforehand.
Todo:

Allow specifying destination prefix before packing

---

conda_pack/core.py
conda_pack/scripts/posix/activate
conda_pack/scripts/posix/deactivate
conda_pack/tests/conftest.py
conda_pack/tests/test_core.py
testing/env_yamls/has_conda.yml
testing/setup_envs.sh

Allows conda to be a package installed in the environment, and makes the packaged environment work with conda after unpacking. Also allows the root environment to be packaged (although there may be more files we'll want to add to `ignore`).
Note that this still doesn't play well with conda-proper's activate/deactivate scripts since we replace them with our own. Both `conda activate environment` and `source activate environment` will work, but `source deactivate` afterwards will leave the environment variables in a bit of a broken state. Since the environment variables used to manage conda's state during activate/deactivate cycles are internal I'm not sure if it'd be wise to mimic those. `source environment/bin/activate` followed by `source deactivate` will continue to work as expected. …

Allow conda in environments

---

conda_pack/core.py

if conda package contains symlink, then conda-meta/*.json conatins  entry of symlink.
so while generating list of files of a prefix. symlink needs to added as separate file.
eg assume a conda package contains 
a_bin -> ./bin/
now conda-meta/*json file have a entry corresponds to it
```
{
"_path": "a_bin",
"path_type": "softlink",
"size_in_bytes": 4096
}
```
but `load_files(prefix): `function returns set(a_bin/file1, a_bin/file2, a_bin/file3)  
hence if failed at targets.difference(all_files)

Handling case if dependencies have symlink

---

docs/source/index.rst

Can't run *directly* using the python in the environment, as it may try to edit itself. Any other version of python works though, as does having the script be the entry point.
Fixes #40.

Fix conda-unpack example

---

conda_pack/compat.py
conda_pack/core.py
conda_pack/tests/test_core.py

On Linux rewriting a running executable file is forbidden. Python is
required for running `conda-unpack`, and *some* versions of python have
an absolute path in them - this can cause problems when the packaged
python is the one running the `conda-unpack` script.
Since the absolute path embedded in the python binary is not important
for normal use, we skip rewriting it when run from `conda-unpack` -
avoiding the issue entirely. Note that we still rewrite the prefix when
using a specified destination prefix.
Fixes #47.

Skip fixing prefix in python exe in conda-unpack

---

setup.cfg
setup.py

With the new windows support, we needed a few changes to these files
before release.
- Depend on setuptools
- Can now build a universal wheel

Cleanup setup.py/setup.cfg

---

conda_pack/_progress.py
conda_pack/cli.py
conda_pack/compat.py
conda_pack/core.py
conda_pack/formats.py
conda_pack/tests/test_formats.py

This adds support for parallelizing file compression for `.tar.gz` and `.tar.bz2` files. This scales ~linearly, and can provide major speedups for higher compression levels.
The default is still single threaded, but you can use `--n-threads`/`-j` to set the number of threads. `-1` indicates use the number of threads as cores.
Also fixes our test suite to test both with and without symlinks on all platorms (explicitly skipping where unsupported). This improves test coverage on my machine.

Add support for parallel packaging

---

conda_pack/core.py
conda_pack/tests/test_core.py
testing/setup_envs.sh

_Builds on #54._
If the environment being packed up contains conda, we shouldn't replace the activate/deactivate scripts. The `conda-pack` scripts are not designed to support the activation of sub-environments, only the root. If `conda` is present, then presumably users of that environment might wish to use it to create and activate new sub-environments.

Keep conda's activate/deactivate scripts

---

conda_pack/scripts/posix/activate
conda_pack/tests/test_core.py
testing/setup_envs.sh

`activate` and `deactivate` still exist but not anymore always but only in certain situations. Use them when available.
This is only a partial fix for #76, `test_pack_with_conda[True]` still fails but this may be unrelated.

Fixes for changes in conda 4.7

---

conda_pack/scripts/posix/activate
conda_pack/scripts/posix/deactivate

Currently everything in the environment scripts folder is ran but only `*.sh` files should be used when (de)activating environments ([see here](https://github.com/conda/conda/blob/8232664e43c323e8381ced751c4c80411f4ee4ee/conda/activate.py#L644-L652)).

Only (de)activate using *.sh

---

conda_pack/core.py
conda_pack/tests/test_core.py

Conda changed its activation scripts, which broke our windows tests.
This fixes those, as well as a lingering issue with pip/conda
compatibility checking.
In the case of packaging an environment that contains conda with a
specified destination prefix (``--dest-prefix``) on windows, things
still are slightly off. When conda is present and the destination is
specified we leave conda's activation scripts as is (don't provide our
own). Conda's new activation scripts for windows no longer work without
a base conda install AFAICT. Since this use case is small, the user
likely already has conda, and I don't see a good work around for this,
we fix the test and move on for now.

Windows test fixes

---

conda_pack/core.py
conda_pack/scripts/posix/activate

Previously we'd ignore LICENSE.txt in the of an environment directory.
In previous conda versions this would be the anaconda license, but in
new releases this file doesn't normally exist. However, some packages
(e.g. tomopy) do include this file in their package (probably
erroneously, as LICENSE.txt in a root directory has nothing specific to
do with their package). By dropping it during collection our pip
clobbering detection logic would trigger, resulting in failure.
Also fixes a small bug in the posix activate script that resulted in
some noisy output.

Don't drop LICENSE.txt

---

conda_pack/cli.py
conda_pack/core.py

`*.pth` files can contain executable lines because reasons (these always start with `import`). We need to skip these when detecting editable packages.
Also tweaks a few docstrings before release.
Fixes #83.

Skip import lines in .pth files 

---

conda_pack/formats.py

Fixes #99 and duplicates.
Here's an example of the new messaging:
```
Collecting packages...
Packing environment at '/home/builder/miniconda3/envs/ptest' to 'ptest.zip'
[                                        ] | 1% Completed |  0.5s
CondaPackError: 
The following conda package file is a symbolic link that does not match an
existing file within the same package:
matplotlib-3.1.1-py37h5429711_0: lib/libtcl.so
It is likely this link points to a file brought into the environment by
a dependency. Unfortunately, conda-pack does not support this practice
unless the --zip-symlinks option is engaged, or unless a tar-based 
archive format is used. See "conda-pack --help" for more information
about the --zip-symlinks option.
```

Provide a proper warning about dangling symbolic links and zip files

---

.github/workflows/main.yml
testing/setup_envs.sh

The Mac runner has been improved allowing a simplification of this action by allowing us to fix the location of CONDA_ROOT more simply to GITHUB_WORKSPACE/..

Simplify workflow based on updated runners

---

.github/workflows/main.yml
.gitignore
conda_pack/tests/conftest.py
conda_pack/tests/test_cli.py
conda_pack/tests/test_core.py
testing/setup_envs.sh

This creates a full conda environment in which to host the testing environments, including the package cache itself. This gives us full control over the package cache for testing, so we can enable new tests that manipulate the package cache without disrupting developer's local work.

Build a full conda tree for the testbed

---

conda_pack/cli.py
conda_pack/core.py
conda_pack/formats.py
conda_pack/scripts/posix/parcel
conda_pack/tests/test_core.py
docs/source/index.rst
docs/source/parcel.rst
setup.cfg

Parcels and conda-packs are in spitting distance of each other:
- Parcels include the base name of the directory in the archive, whereas conda-pack archives, by default, do not—but can do so optionally with the `--arcroot` option.
- Parcels are given a `.parcel` suffix but in fact are in the `.tar.gz` format
- Parcels have some additional metadata in the `meta/` subdirectory:
- A `parcel.json` file providing important information about the parcel;
- An activation script. The name is provided in `parcel.json`, and we have called it `conda_env.sh`.
- Parcels are immutable, which from a `conda-pack` perspective means they need the `--dest-prefix` supplied, and it must match where the parcel is unpacked.
This code bridges this gap and in doing so allows conda-pack to build parcels.

Add parcel support

---

conda_pack/core.py
testing/env_yamls/has_conda.yml

Fixes #145, which is caused by a small handful of malformed conda packages. Most conda packages do not create files in the `info/` subdirectory of a conda environment. The current version of `conda-pack` ignores this directory when packing. But a few malformed conda packages do install files into this directory. So by ignoring this directory, conda-pack spits out missing file errors.

Handle malformed conda packages with info/ files in paths.json

---

conda_pack/core.py
conda_pack/tests/test_core.py
testing/setup_envs.sh

One of the challenges with the 'missing files' exception is that there is no information about what those missing files _are_. This adjustment to that exception message fixes that by providing a partial listing of the files that were discovered missing.
For example, the `py36_missing_files` environment in the testbed now has all of the `.py` files from the `toolz` package removed. The error message returned when packing that environment looks like this now:
```
Collecting packages...
CondaPackError: 
Files managed by conda were found to have been deleted/overwritten in the
following packages:
- toolz 0.10.0:
lib/python3.6/site-packages/toolz/__init__.py
lib/python3.6/site-packages/toolz/_signatures.py
lib/python3.6/site-packages/toolz/compatibility.py
+ 5 others
This is usually due to …
```

Improve the missing file messaging with a partial listing of the missing files

---

conda_pack/formats.py
docs/source/squashfs.rst

SquashFS use zstd as default

---

conda_pack/cli.py
conda_pack/core.py
conda_pack/formats.py
conda_pack/tests/test_core.py
conda_pack/tests/test_formats.py

This enables maximum compression compared to gzip, bzip2 and zstd and is possible with pure Python 3 without any additional dependencies like libarchive-c.

Implement tar.xz support

---

conda_pack/prefixes.py

I have recently started observing that conda-unpack was not properly fixing prefixes of entry points in Windows packages installed with `pip install .`.
This is because conda-pack assumes that the placeholder is in lower-case. But by inspecting the entry point binary I found this not to be the case. This PR solves the issue by trying to fix the entry point using both lower-case and mixed-case forms of the placeholder.
environment:
```
ca-certificates           2021.7.5             haa95532_1
certifi                   2021.5.30        py39haa95532_0
openssl                   1.1.1l               h2bbff1b_0
pip                       21.2.4           py38haa95532_0
python                    3.9.6                h6244533_1
setuptools                52.0.0           py39haa95532_0
snake …
```

Fixes to Windows prefix changes

---

conda_pack/core.py

The current implementation of [find_site_packages](https://github.com/conda/conda-pack/blob/ecede405fa4554d3b986256c0456959919039ea0/conda_pack/core.py#L551:575)
extracts the Python version from a string with
https://github.com/conda/conda-pack/blob/ecede405fa4554d3b986256c0456959919039ea0/conda_pack/core.py#L573
This returns `3.1` for Python 3.10, which is not what we want.
This may also address the issue reported in #198.

Support Python 3.10 in `find_site_packages`

---

conda_pack/core.py

A space was missing when running conda-unpack --help between `unarchiving` and `Cleans`
```$ conda unpack --help
usage: conda-unpack [-h] [--version]
Finish unpacking the environment after unarchiving.Cleans up absolute prefixes in any remaining
files
optional arguments:
-h, --help  show this help message and exit
--version   Show version then exit```
Now it should be
```
```
$ conda unpack --help
usage: conda-unpack [-h] [--version]
Finish unpacking the environment after unarchiving. Cleans up absolute prefixes in any remaining
files
optional arguments:
-h, --help  show this help message and exit
--version   Show version then exit```

Add fix for core.py missing space

---

.github/workflows/main.yml
README.md

The minor modifications needed for renaming the default branch from master to main.
Xref: https://github.com/conda/conda/issues/11517

Rename master to main

---

.github/workflows/main.yml

Re-enable coverage reporting to see what parts of the code is tested (or even if there is potential dead=unused code).
Coverage is over >77%, see https://app.codecov.io/gh/conda/conda-pack/pull/251 :) 
The is already a codecov badge in the README which is still correct, but there seems to be no previous coverage data.

Re-enable coverage reporting

---

conda_pack/cli.py
conda_pack/formats.py
news/252-allow-compression-level-in-zip-files

Since Python 3.7 the Python zipfile module has allowed setting the
default compression level in zipfiles using the `compresslevel`
argument.
Pass the compression level specified on the command line to the ZipFile class.

Allow the compression level to be set in zip files

---

conda_pack/core.py
conda_pack/prefixes.py
news/275-fix-windows-seperator

I'm experiencing a bug that doesn't allow me to unpack environments on Windows machines, the error presents like so
This reproduction is quite minimal, and it seems to affect all packed files with `mode="text"`, so I can only assume it's caused by a mismatching path separator - the prefix is defined [here](https://github.com/conda/conda-pack/blob/031be65749011273c2ffbaf76a47083012f2912d/conda_pack/core.py#L1003C14-L1003C14) using the Windows separator `\`, and the suffix is modified [here](https://github.com/conda/conda-pack/blob/031be65749011273c2ffbaf76a47083012f2912d/conda_pack/prefixes.py#L63) to use the separator `/`, resulting in the mismatch. This PR also modifies the prefix in the same manner, so that the entire path uses the separator `/` in these cases.
---
- To see the specific …

Fix path separator on Windows distributions

---

conda_pack/prefixes.py
news/osx-arm64-support

codesign binaries on osx-arm64

---

.github/workflows/publish.yml

This is already set up on the PyPI side. I created the workflow using https://pgjones.dev/blog/trusted-plublishing-2023/ and https://docs.pypi.org/trusted-publishers/using-a-publisher/

Upload releases to PyPI using trusted publishing

---

conda_pack/cli.py
conda_pack/core.py
conda_pack/tests/test_core.py
news/295-create-output-dir-if-missing-and-force

I've had a couple of occasions where I've used `conda-pack` and asked it to output to a directory that doesn't exist by accident. The packing goes ahead and the operation eventually fails in the `shutil.move()` command right at the end.
I wanted to make it fail early instead or, if `force` was used, to create the directory.
I've gotten it into a 'good enough' working state, and can tidy it up further if you would be open to merging this change.

Create the output directory if its missing and `force` is used, otherwise raise 

---

conda_pack/formats.py
news/306-fix-hard-link-failure

Can not create hard-link on Linux when source file is owned by root but conda-pack runs as non-root user.
Fixing issue #248, when `conda` is installed as `root` and `conda-pack` runs as non-root, hard-linking activate script from conda installation directory to temp folder fails. So we check that source and destination are by the same user and on the same filesystem before deciding to use more efficient link instead of costlier copy.

Fix in SquashFSArchive._add #248

---

conda_pack/core.py
news/support-pixi-environments.md

I tried to use conda-pack with environments created using [pixi](https://pixi.sh). This caused a few issues due to slight variations in the content of the conda-mata files. (E.g. `info['link']` was "null" in my files, and I don't have a `conda-meta/history` file). 
Have added few checks to the code which makes conda-pack work with environments created with pixi. 
I don't know if there is a standard for the conda-meta stuff. If so, the real fix should be in pixi of course. But I hope you will consider my PR anyway.

Fix crash when using conda-pack on environments created with pixi

---

conda_pack/cli.py
conda_pack/core.py
conda_pack/formats.py
conda_pack/tests/test_formats.py

Existing formats do not provide a straightforward way to clone the environment without making an intermediate archive. Even with disabled compression, they impact execution time and use extra disk space. The no-archive is a new format that addresses both aspects. It is 4x faster for local environment cloning on basic scenarios (i.e. github.com/idamlaj/dist-demo) and uses no extra disk space.

Add no-archive format for fast environment clone

---

.github/workflows/main.yml
conda_pack/core.py
conda_pack/scripts/posix/activate.fish
conda_pack/tests/test_core.py

This adds support for the fish shell #72
Test plan:
```
$ pytest conda_pack/tests/test_core.py
```
manual tests
```
$ conda-pack
$ tar xvf ~/conda-pack/conda-pack-3.10.tar.gz; . bin/activate.fish
$ which python3
$ deactivate
```

activate.fish: support activating conda in fish shells

---

.github/workflows/main.yml

follow up from #376 
you'll need to make some changes on the settings pages
then, a multi-step change is needed:
step 1:
step 2:
Once the above things have been set, the docs _should_ push on any tag that gets pushed to this repo.

Add the deploy step for gh pages

---

.github/workflows/main.yml
.pre-commit-config.yaml

We only upload docs when a release is tagged, same constrain has to be applied also to the deploy to avoid artifact not found errors.
This is done under the assumption that it is better to only update the documentation when a release is done. Otherwise we potentially advertise unreleased features in the docs.
While at it also schema checking the changed workflow file.

Only deploy docs when release is tagged

---

Changelog.md

Backfilling the changelog for record-keeping

Update changelog with 0.8.0 and 0.8.1
